// ─────────────────────────────────────────────────────────────────────────────
// frontend/src/services/mockData.ts
// Realistic initial data for Fitness Coach Tracker
// ─────────────────────────────────────────────────────────────────────────────

import type {
  UserProfile,
  FoodItem,
  FoodLogEntry,
  PhysiqueEntry,
  BodyWeightLog,
  WorkoutSession,
  ExerciseDefinition,
  FormCorrectionGuide,
  PaymentPlan,
  PaymentTransaction,
  BiWeeklyMeetup,
  ClientCoachRecord,
  NotificationItem,
} from '../types/fitness';

export const initialUsers: UserProfile[] = [
  {
    id: 'user_alex',
    name: 'Alex Rivers',
    email: 'alex.rivers@fitness.app',
    role: 'client',
    roleTitle: 'Athlete / Client',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 234-5678',
    heightCm: 178,
    startingWeightKg: 74.2,
    currentWeightKg: 76.8,
    goalWeightKg: 80.0,
    targetCalories: 2650,
    targetProteinG: 175,
    targetCarbsG: 300,
    targetFatG: 70,
    targetFiberG: 35,
    targetWaterMl: 3500,
    targetWorkoutsPerWeek: 5,
    assignedCoach: 'Coach Pat',
    activeTier: 'elite',
    subscriptionExpiry: '2026-12-31',
    password: 'fitness123',
    status: 'active',
    joinedDate: '2026-01-10',
  },
  {
    id: 'coach_pat',
    name: 'Coach Pat',
    email: 'coach.pat@fitness.app',
    role: 'coach',
    roleTitle: 'Head Strength & Physique Coach (Admin / CSCS)',
    avatar: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 890-1234',
    heightCm: 185,
    startingWeightKg: 92,
    currentWeightKg: 90,
    goalWeightKg: 90,
    targetCalories: 3200,
    targetProteinG: 220,
    targetCarbsG: 360,
    targetFatG: 85,
    targetFiberG: 45,
    targetWaterMl: 4500,
    targetWorkoutsPerWeek: 6,
    assignedCoach: 'Self',
    activeTier: 'elite',
    subscriptionExpiry: '2099-12-31',
    password: 'coach123',
    status: 'active',
    joinedDate: '2025-06-01',
  },
  {
    id: 'staff_sarah',
    name: 'Sarah Lin',
    email: 'sarah.lin@fitness.app',
    role: 'staff',
    roleTitle: 'Staff Performance Trainer & Nutrition Specialist',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 456-7890',
    heightCm: 168,
    startingWeightKg: 62,
    currentWeightKg: 62,
    goalWeightKg: 63,
    targetCalories: 2100,
    targetProteinG: 140,
    targetCarbsG: 220,
    targetFatG: 55,
    targetFiberG: 30,
    targetWaterMl: 3000,
    targetWorkoutsPerWeek: 4,
    assignedCoach: 'Coach Pat',
    activeTier: 'elite',
    subscriptionExpiry: '2099-12-31',
    password: 'staff123',
    status: 'active',
    joinedDate: '2025-09-15',
  },
  {
    id: 'user_marcus',
    name: 'Marcus Vance',
    email: 'marcus.vance@fitness.app',
    role: 'client',
    roleTitle: 'Athlete / Powerbuilding Focus',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 345-6789',
    heightCm: 182,
    startingWeightKg: 85.0,
    currentWeightKg: 88.5,
    goalWeightKg: 90.0,
    targetCalories: 3100,
    targetProteinG: 200,
    targetCarbsG: 380,
    targetFatG: 80,
    targetFiberG: 40,
    targetWaterMl: 4000,
    targetWorkoutsPerWeek: 5,
    assignedCoach: 'Coach Pat',
    activeTier: 'elite',
    subscriptionExpiry: '2026-11-30',
    password: 'fitness123',
    status: 'active',
    joinedDate: '2026-02-01',
  },
  {
    id: 'user_elena',
    name: 'Elena Rostova',
    email: 'elena.rostova@fitness.app',
    role: 'client',
    roleTitle: 'Athlete / Glute & Hypertrophy Focus',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 678-9012',
    heightCm: 165,
    startingWeightKg: 58.0,
    currentWeightKg: 56.5,
    goalWeightKg: 55.0,
    targetCalories: 1950,
    targetProteinG: 135,
    targetCarbsG: 210,
    targetFatG: 50,
    targetFiberG: 30,
    targetWaterMl: 2800,
    targetWorkoutsPerWeek: 4,
    assignedCoach: 'Coach Pat',
    activeTier: 'pro',
    subscriptionExpiry: '2026-10-15',
    password: 'fitness123',
    status: 'active',
    joinedDate: '2026-03-12',
  },
  {
    id: 'staff_david',
    name: 'David Miller',
    email: 'david.miller@fitness.app',
    role: 'staff',
    roleTitle: 'Staff Biomechanics & Movement Coach',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 789-0123',
    heightCm: 180,
    startingWeightKg: 78,
    currentWeightKg: 78,
    goalWeightKg: 80,
    targetCalories: 2700,
    targetProteinG: 180,
    targetCarbsG: 310,
    targetFatG: 70,
    targetFiberG: 35,
    targetWaterMl: 3500,
    targetWorkoutsPerWeek: 5,
    assignedCoach: 'Coach Pat',
    activeTier: 'elite',
    subscriptionExpiry: '2099-12-31',
    password: 'staff123',
    status: 'active',
    joinedDate: '2025-11-01',
  },
];

export const initialFoodDatabase: FoodItem[] = [
  { id: 'f1', name: 'Grilled Chicken Breast', brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 165, protein: 31.0, carbs: 0, fat: 3.6, fiber: 0, sodiumMg: 74, potassiumMg: 256, ironMg: 1.0 },
  { id: 'f2', name: 'Rolled Oats', brand: 'Quaker', servingSize: 50, servingUnit: 'g', calories: 187, protein: 6.5, carbs: 33.0, fat: 3.2, fiber: 5.0, sodiumMg: 2, potassiumMg: 180, ironMg: 2.1 },
  { id: 'f3', name: 'Whole Large Egg', brand: 'Generic', servingSize: 50, servingUnit: 'g (1 egg)', calories: 72, protein: 6.3, carbs: 0.4, fat: 4.8, fiber: 0, sodiumMg: 71, calciumMg: 28, ironMg: 0.9 },
  { id: 'f4', name: 'Egg Whites', brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 52, protein: 11.0, carbs: 0.7, fat: 0.2, fiber: 0, sodiumMg: 166, potassiumMg: 163 },
  { id: 'f5', name: 'Whey Protein Isolate', brand: 'Optimum Nutrition', servingSize: 30, servingUnit: 'g (1 scoop)', calories: 120, protein: 24.0, carbs: 1.5, fat: 1.0, fiber: 0, sodiumMg: 130, calciumMg: 140 },
  { id: 'f6', name: 'Jasmine White Rice (Cooked)', brand: 'Generic', servingSize: 150, servingUnit: 'g', calories: 195, protein: 3.6, carbs: 42.5, fat: 0.4, fiber: 0.6, sodiumMg: 1, potassiumMg: 52 },
  { id: 'f7', name: 'Brown Rice (Cooked)', brand: 'Generic', servingSize: 150, servingUnit: 'g', calories: 168, protein: 3.8, carbs: 35.0, fat: 1.4, fiber: 2.7, sodiumMg: 2, potassiumMg: 118 },
  { id: 'f8', name: 'Atlantic Salmon Fillet', brand: 'Generic', servingSize: 120, servingUnit: 'g', calories: 248, protein: 24.5, carbs: 0, fat: 15.5, fiber: 0, sodiumMg: 60, potassiumMg: 430 },
  { id: 'f9', name: 'Lean Ground Beef (93/7)', brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 172, protein: 21.0, carbs: 0, fat: 9.0, fiber: 0, sodiumMg: 68, ironMg: 2.3 },
  { id: 'f10', name: 'Greek Yogurt 0% Fat', brand: 'Fage', servingSize: 170, servingUnit: 'g', calories: 90, protein: 18.0, carbs: 5.0, fat: 0, fiber: 0, sodiumMg: 65, calciumMg: 200 },
  { id: 'f11', name: 'Sweet Potato (Baked)', brand: 'Generic', servingSize: 150, servingUnit: 'g', calories: 135, protein: 3.0, carbs: 31.0, fat: 0.2, fiber: 4.5, potassiumMg: 540, calciumMg: 45 },
  { id: 'f12', name: 'Fresh Avocado', brand: 'Generic', servingSize: 75, servingUnit: 'g (1/2 avocado)', calories: 120, protein: 1.5, carbs: 6.4, fat: 11.0, fiber: 5.0, potassiumMg: 360 },
  { id: 'f13', name: 'Peanut Butter (Natural)', brand: 'Generic', servingSize: 32, servingUnit: 'g (2 tbsp)', calories: 190, protein: 8.0, carbs: 7.0, fat: 16.0, fiber: 2.0, sodiumMg: 5, potassiumMg: 200 },
  { id: 'f14', name: 'Almonds (Raw)', brand: 'Generic', servingSize: 30, servingUnit: 'g (approx 23 nuts)', calories: 170, protein: 6.0, carbs: 6.0, fat: 15.0, fiber: 3.5, calciumMg: 75, ironMg: 1.0 },
  { id: 'f15', name: 'Steamed Broccoli', brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 35, protein: 2.4, carbs: 7.2, fat: 0.4, fiber: 2.6, sodiumMg: 41, potassiumMg: 316, calciumMg: 47 },
  { id: 'f16', name: 'Medium Banana', brand: 'Generic', servingSize: 118, servingUnit: 'g (1 fruit)', calories: 105, protein: 1.3, carbs: 27.0, fat: 0.3, fiber: 3.1, potassiumMg: 422 },
  { id: 'f17', name: 'Fresh Blueberries', brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 57, protein: 0.7, carbs: 14.5, fat: 0.3, fiber: 2.4, potassiumMg: 77 },
  { id: 'f18', name: 'Cottage Cheese 1% Fat', brand: 'Good Culture', servingSize: 113, servingUnit: 'g (1/2 cup)', calories: 80, protein: 14.0, carbs: 3.0, fat: 1.5, fiber: 0, sodiumMg: 350, calciumMg: 100 },
  { id: 'f19', name: 'Extra Virgin Olive Oil', brand: 'Generic', servingSize: 14, servingUnit: 'g (1 tbsp)', calories: 119, protein: 0, carbs: 0, fat: 13.5, fiber: 0 },
  { id: 'f20', name: 'Canned Tuna in Water', brand: 'StarKist', servingSize: 100, servingUnit: 'g drained', calories: 116, protein: 26.0, carbs: 0, fat: 1.0, fiber: 0, sodiumMg: 320 },
  { id: 'f21', name: 'Whole Grain Bread', brand: 'Ezekiel 4:9', servingSize: 34, servingUnit: 'g (1 slice)', calories: 80, protein: 5.0, carbs: 15.0, fat: 0.5, fiber: 3.0, sodiumMg: 75 },
  { id: 'f22', name: 'Almond Milk (Unsweetened)', brand: 'Silk', servingSize: 240, servingUnit: 'ml (1 cup)', calories: 30, protein: 1.0, carbs: 1.0, fat: 2.5, fiber: 1.0, calciumMg: 450 },
  { id: 'f23', name: 'Cooked Quinoa', brand: 'Generic', servingSize: 150, servingUnit: 'g', calories: 180, protein: 6.0, carbs: 32.0, fat: 2.8, fiber: 4.2, ironMg: 2.1 },
  { id: 'f24', name: 'Grass-Fed Beef Sirloin Steak', brand: 'Generic', servingSize: 150, servingUnit: 'g', calories: 270, protein: 34.0, carbs: 0, fat: 13.5, fiber: 0, ironMg: 3.2 },
];

export const initialFoodLogs: FoodLogEntry[] = [
  {
    id: 'log_1',
    date: '2026-08-19',
    mealCategory: 'breakfast',
    food: initialFoodDatabase[1], // Rolled Oats
    servings: 1.5,
    totalCalories: 280,
    totalProtein: 9.8,
    totalCarbs: 49.5,
    totalFat: 4.8,
    totalFiber: 7.5,
    loggedAt: '07:30 AM',
  },
  {
    id: 'log_2',
    date: '2026-08-19',
    mealCategory: 'breakfast',
    food: initialFoodDatabase[4], // Whey Isolate
    servings: 1,
    totalCalories: 120,
    totalProtein: 24.0,
    totalCarbs: 1.5,
    totalFat: 1.0,
    totalFiber: 0,
    loggedAt: '07:30 AM',
  },
  {
    id: 'log_3',
    date: '2026-08-19',
    mealCategory: 'breakfast',
    food: initialFoodDatabase[15], // Banana
    servings: 1,
    totalCalories: 105,
    totalProtein: 1.3,
    totalCarbs: 27.0,
    totalFat: 0.3,
    totalFiber: 3.1,
    loggedAt: '07:35 AM',
  },
  {
    id: 'log_4',
    date: '2026-08-19',
    mealCategory: 'lunch',
    food: initialFoodDatabase[0], // Grilled Chicken
    servings: 2,
    totalCalories: 330,
    totalProtein: 62.0,
    totalCarbs: 0,
    totalFat: 7.2,
    totalFiber: 0,
    loggedAt: '12:45 PM',
  },
  {
    id: 'log_5',
    date: '2026-08-19',
    mealCategory: 'lunch',
    food: initialFoodDatabase[5], // Jasmine Rice
    servings: 1.5,
    totalCalories: 292,
    totalProtein: 5.4,
    totalCarbs: 63.8,
    totalFat: 0.6,
    totalFiber: 0.9,
    loggedAt: '12:45 PM',
  },
  {
    id: 'log_6',
    date: '2026-08-19',
    mealCategory: 'lunch',
    food: initialFoodDatabase[14], // Steamed Broccoli
    servings: 1.5,
    totalCalories: 52,
    totalProtein: 3.6,
    totalCarbs: 10.8,
    totalFat: 0.6,
    totalFiber: 3.9,
    loggedAt: '12:45 PM',
  },
  {
    id: 'log_7',
    date: '2026-08-19',
    mealCategory: 'snack',
    food: initialFoodDatabase[9], // Greek Yogurt
    servings: 1,
    totalCalories: 90,
    totalProtein: 18.0,
    totalCarbs: 5.0,
    totalFat: 0,
    totalFiber: 0,
    loggedAt: '04:15 PM',
  },
  {
    id: 'log_8',
    date: '2026-08-19',
    mealCategory: 'snack',
    food: initialFoodDatabase[13], // Almonds
    servings: 1,
    totalCalories: 170,
    totalProtein: 6.0,
    totalCarbs: 6.0,
    totalFat: 15.0,
    totalFiber: 3.5,
    loggedAt: '04:15 PM',
  },
];

export const initialPhysiqueLogs: PhysiqueEntry[] = [
  {
    id: 'physique_w1',
    date: '2026-06-24',
    weekNumber: 1,
    frontPhoto: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&auto=format&fit=crop&q=80',
    sidePhoto: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600&auto=format&fit=crop&q=80',
    backPhoto: 'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?w=600&auto=format&fit=crop&q=80',
    weightKg: 74.2,
    bodyFatPercent: 16.4,
    measurements: {
      chestCm: 101.5,
      waistCm: 84.0,
      hipsCm: 96.0,
      leftArmCm: 35.0,
      rightArmCm: 35.2,
      leftThighCm: 56.5,
      rightThighCm: 56.5,
      shouldersCm: 118.0,
      neckCm: 38.0,
    },
    notes: 'Starting cycle with Coach Pat. Focus on clean surplus and progressive overload on compound lifts.',
    coachFeedback: 'Great baseline form. Ensure sleep is above 7.5 hrs. Target +0.3 to +0.4kg per week.',
    reviewedByCoach: true,
  },
  {
    id: 'physique_w4',
    date: '2026-07-22',
    weekNumber: 4,
    frontPhoto: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80',
    sidePhoto: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&auto=format&fit=crop&q=80',
    backPhoto: 'https://images.unsplash.com/photo-1584466977772-e5994a2c3a5b?w=600&auto=format&fit=crop&q=80',
    weightKg: 75.5,
    bodyFatPercent: 15.8,
    measurements: {
      chestCm: 103.0,
      waistCm: 83.5,
      hipsCm: 96.5,
      leftArmCm: 35.8,
      rightArmCm: 36.0,
      leftThighCm: 57.5,
      rightThighCm: 57.5,
      shouldersCm: 119.5,
      neckCm: 38.2,
    },
    notes: 'Upper body density improving noticeably. Chest and lats feel thicker.',
    coachFeedback: 'Awesome waist-to-shoulder ratio improvement! Adding 100 kcal on leg days.',
    reviewedByCoach: true,
  },
  {
    id: 'physique_w8',
    date: '2026-08-19',
    weekNumber: 8,
    frontPhoto: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
    sidePhoto: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&auto=format&fit=crop&q=80',
    backPhoto: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&auto=format&fit=crop&q=80',
    weightKg: 76.8,
    bodyFatPercent: 15.1,
    measurements: {
      chestCm: 105.0,
      waistCm: 83.0,
      hipsCm: 97.0,
      leftArmCm: 36.6,
      rightArmCm: 36.8,
      leftThighCm: 58.8,
      rightThighCm: 59.0,
      shouldersCm: 121.5,
      neckCm: 38.5,
    },
    notes: 'Current week 8 check-in. Vascularity in arms and shoulders showing through.',
    coachFeedback: 'Solid progress for bi-weekly check-in meetup with Coach Pat this Friday!',
    reviewedByCoach: true,
  },
];

export const initialWeightLogs: BodyWeightLog[] = [
  { id: 'w1', date: '2026-07-21', weightKg: 75.3, timeOfDay: 'morning', bmi: 23.8 },
  { id: 'w2', date: '2026-07-23', weightKg: 75.4, timeOfDay: 'morning', bmi: 23.8 },
  { id: 'w3', date: '2026-07-26', weightKg: 75.6, timeOfDay: 'morning', bmi: 23.9 },
  { id: 'w4', date: '2026-07-29', weightKg: 75.7, timeOfDay: 'morning', bmi: 23.9 },
  { id: 'w5', date: '2026-08-01', weightKg: 75.9, timeOfDay: 'morning', bmi: 24.0 },
  { id: 'w6', date: '2026-08-04', weightKg: 76.0, timeOfDay: 'morning', bmi: 24.0 },
  { id: 'w7', date: '2026-08-07', weightKg: 76.2, timeOfDay: 'morning', bmi: 24.0 },
  { id: 'w8', date: '2026-08-10', weightKg: 76.3, timeOfDay: 'morning', bmi: 24.1 },
  { id: 'w9', date: '2026-08-13', weightKg: 76.5, timeOfDay: 'morning', bmi: 24.1 },
  { id: 'w10', date: '2026-08-16', weightKg: 76.6, timeOfDay: 'morning', bmi: 24.2 },
  { id: 'w11', date: '2026-08-18', weightKg: 76.7, timeOfDay: 'morning', bmi: 24.2 },
  { id: 'w12', date: '2026-08-19', weightKg: 76.8, timeOfDay: 'morning', bmi: 24.2 },
];

export const initialWorkouts: WorkoutSession[] = [
  {
    id: 'wo_1',
    date: '2026-08-18',
    title: 'Push Power & Hypertrophy',
    splitType: 'Push',
    durationMinutes: 68,
    energyLevel: 5,
    completed: true,
    totalVolumeKg: 6420,
    totalSets: 14,
    totalReps: 122,
    notes: 'Hit a new PR on Barbell Bench Press (95kg for 5 reps)! Rest times kept to 90s.',
    exercises: [
      {
        exerciseId: 'ex_bench',
        exerciseName: 'Barbell Flat Bench Press',
        targetMuscle: 'Chest',
        sets: [
          { setNumber: 1, weightKg: 70, reps: 10, rpe: 7, completed: true },
          { setNumber: 2, weightKg: 85, reps: 8, rpe: 8, completed: true },
          { setNumber: 3, weightKg: 95, reps: 5, rpe: 9, completed: true, isPR: true },
          { setNumber: 4, weightKg: 90, reps: 6, rpe: 9, completed: true },
        ],
      },
      {
        exerciseId: 'ex_incline_db',
        exerciseName: 'Incline Dumbbell Press',
        targetMuscle: 'Chest',
        sets: [
          { setNumber: 1, weightKg: 30, reps: 10, rpe: 8, completed: true },
          { setNumber: 2, weightKg: 32, reps: 8, rpe: 8.5, completed: true },
          { setNumber: 3, weightKg: 32, reps: 8, rpe: 9, completed: true },
        ],
      },
      {
        exerciseId: 'ex_ohp',
        exerciseName: 'Standing Overhead Barbell Press',
        targetMuscle: 'Shoulders',
        sets: [
          { setNumber: 1, weightKg: 50, reps: 8, rpe: 7.5, completed: true },
          { setNumber: 2, weightKg: 55, reps: 6, rpe: 8.5, completed: true },
          { setNumber: 3, weightKg: 55, reps: 6, rpe: 9, completed: true },
        ],
      },
      {
        exerciseId: 'ex_cable_tricep',
        exerciseName: 'Cable Rope Tricep Pushdown',
        targetMuscle: 'Triceps',
        sets: [
          { setNumber: 1, weightKg: 27.5, reps: 15, rpe: 8, completed: true },
          { setNumber: 2, weightKg: 32.5, reps: 12, rpe: 8.5, completed: true },
          { setNumber: 3, weightKg: 32.5, reps: 12, rpe: 9, completed: true },
          { setNumber: 4, weightKg: 35.0, reps: 10, rpe: 9.5, completed: true },
        ],
      },
    ],
  },
  {
    id: 'wo_2',
    date: '2026-08-16',
    title: 'Pull & Lat Thickness',
    splitType: 'Pull',
    durationMinutes: 62,
    energyLevel: 4,
    completed: true,
    totalVolumeKg: 7850,
    totalSets: 15,
    totalReps: 130,
    notes: 'Deadlifts felt smooth. Focus on hip hinge and lats tight against bar.',
    exercises: [
      {
        exerciseId: 'ex_deadlift',
        exerciseName: 'Conventional Barbell Deadlift',
        targetMuscle: 'Back',
        sets: [
          { setNumber: 1, weightKg: 110, reps: 8, rpe: 7, completed: true },
          { setNumber: 2, weightKg: 130, reps: 6, rpe: 8, completed: true },
          { setNumber: 3, weightKg: 145, reps: 5, rpe: 9, completed: true },
          { setNumber: 4, weightKg: 145, reps: 5, rpe: 9, completed: true },
        ],
      },
      {
        exerciseId: 'ex_pullup',
        exerciseName: 'Weighted Pull-Ups',
        targetMuscle: 'Back',
        sets: [
          { setNumber: 1, weightKg: 10, reps: 8, rpe: 8, completed: true },
          { setNumber: 2, weightKg: 10, reps: 7, rpe: 8.5, completed: true },
          { setNumber: 3, weightKg: 5, reps: 8, rpe: 9, completed: true },
        ],
      },
      {
        exerciseId: 'ex_barbell_row',
        exerciseName: 'Bent-Over Barbell Row',
        targetMuscle: 'Back',
        sets: [
          { setNumber: 1, weightKg: 70, reps: 10, rpe: 7.5, completed: true },
          { setNumber: 2, weightKg: 80, reps: 8, rpe: 8.5, completed: true },
          { setNumber: 3, weightKg: 80, reps: 8, rpe: 9, completed: true },
        ],
      },
      {
        exerciseId: 'ex_bicep_curl',
        exerciseName: 'Incline Dumbbell Bicep Curl',
        targetMuscle: 'Biceps',
        sets: [
          { setNumber: 1, weightKg: 14, reps: 12, rpe: 8, completed: true },
          { setNumber: 2, weightKg: 16, reps: 10, rpe: 8.5, completed: true },
          { setNumber: 3, weightKg: 16, reps: 10, rpe: 9, completed: true },
        ],
      },
    ],
  },
  {
    id: 'wo_3',
    date: '2026-08-14',
    title: 'Leg Quad & Hamstring Focus',
    splitType: 'Legs',
    durationMinutes: 70,
    energyLevel: 4,
    completed: true,
    totalVolumeKg: 9200,
    totalSets: 16,
    totalReps: 145,
    notes: 'Deep squats with pause at bottom. Great quad pump.',
    exercises: [
      {
        exerciseId: 'ex_squat',
        exerciseName: 'Barbell Back Squat',
        targetMuscle: 'Quadriceps',
        sets: [
          { setNumber: 1, weightKg: 90, reps: 10, rpe: 7, completed: true },
          { setNumber: 2, weightKg: 110, reps: 8, rpe: 8, completed: true },
          { setNumber: 3, weightKg: 125, reps: 6, rpe: 9, completed: true },
          { setNumber: 4, weightKg: 125, reps: 6, rpe: 9, completed: true },
        ],
      },
      {
        exerciseId: 'ex_rdl',
        exerciseName: 'Romanian Deadlift (Dumbbell/Barbell)',
        targetMuscle: 'Hamstrings',
        sets: [
          { setNumber: 1, weightKg: 80, reps: 10, rpe: 7.5, completed: true },
          { setNumber: 2, weightKg: 90, reps: 8, rpe: 8.5, completed: true },
          { setNumber: 3, weightKg: 90, reps: 8, rpe: 9, completed: true },
        ],
      },
      {
        exerciseId: 'ex_leg_press',
        exerciseName: '45-Degree Leg Press',
        targetMuscle: 'Quadriceps',
        sets: [
          { setNumber: 1, weightKg: 180, reps: 12, rpe: 8, completed: true },
          { setNumber: 2, weightKg: 220, reps: 10, rpe: 8.5, completed: true },
          { setNumber: 3, weightKg: 240, reps: 10, rpe: 9, completed: true },
        ],
      },
    ],
  },
];

export const initialExercises: ExerciseDefinition[] = [
  // Commercial Gym
  { id: 'ex_bench', name: 'Barbell Flat Bench Press', muscleGroup: 'Chest', secondaryMuscles: ['Triceps', 'Shoulders'], equipment: 'Gym (Barbell)', isMinimalEquipment: false, difficulty: 'Intermediate', instructions: ['Lie flat on the bench with eyes directly under bar.', 'Grip slightly wider than shoulder width.', 'Lower bar under control to mid-chest, keeping elbows tucked at 45-70 degrees.', 'Drive up through palms, maintaining arch and foot contact.'], tips: ['Retract scapulae before un-racking.', 'Keep wrists neutral.'] },
  { id: 'ex_squat', name: 'Barbell Back Squat', muscleGroup: 'Quadriceps', secondaryMuscles: ['Glutes', 'Hamstrings', 'Core'], equipment: 'Gym (Barbell)', isMinimalEquipment: false, difficulty: 'Intermediate', instructions: ['Rest bar across upper traps or rear delts.', 'Stance shoulder-width with toes slightly flared.', 'Initiate by breaking at hips and knees simultaneously.', 'Descend to parallel or below while keeping chest proud and knees tracking toes.', 'Drive through whole foot.'], tips: ['Take deep breath into abdomen before descent (Valsalva).', 'Avoid knee collapse.'] },
  { id: 'ex_deadlift', name: 'Conventional Barbell Deadlift', muscleGroup: 'Back', secondaryMuscles: ['Hamstrings', 'Glutes', 'Core', 'Quadriceps'], equipment: 'Gym (Barbell)', isMinimalEquipment: false, difficulty: 'Advanced', instructions: ['Stand with mid-foot directly under the bar, shins 1 inch away.', 'Hinge down, grab bar just outside knees.', 'Pull chest tall, pull slack out of the bar, lock lats tight.', 'Push the floor away through mid-foot until standing upright.'], tips: ['Never round the lumbar spine.', 'The bar must drag right up your shins.'] },
  { id: 'ex_ohp', name: 'Overhead Barbell Military Press', muscleGroup: 'Shoulders', secondaryMuscles: ['Triceps', 'Core'], equipment: 'Gym (Barbell)', isMinimalEquipment: false, difficulty: 'Intermediate', instructions: ['Bar resting on front delts/clavicle.', 'Squeeze glutes and abs tight.', 'Press bar vertically in a straight path, moving head back slightly as bar passes nose.', 'Lock out overhead with bar directly over mid-foot.'], tips: ['Avoid excessive lower back hyperextension.', 'Stack elbows directly under wrists.'] },
  { id: 'ex_barbell_row', name: 'Bent-Over Barbell Row', muscleGroup: 'Back', secondaryMuscles: ['Biceps', 'Shoulders', 'Core'], equipment: 'Gym (Barbell)', isMinimalEquipment: false, difficulty: 'Intermediate', instructions: ['Hinge forward to a 45-degree torso angle.', 'Grip barbell overhand or underhand.', 'Pull bar towards lower ribcage/belly button using lats.', 'Squeeze shoulder blades together at top.'], tips: ['Keep spine neutral without jerky momentum.', 'Think about pulling elbows back.'] },
  { id: 'ex_rdl', name: 'Romanian Deadlift (Barbell/Dumbbell)', muscleGroup: 'Hamstrings', secondaryMuscles: ['Glutes', 'Back'], equipment: 'Gym (Barbell)', isMinimalEquipment: false, difficulty: 'Intermediate', instructions: ['Hold weight in front of thighs with slight knee bend.', 'Push hips far back as if touching a wall behind you.', 'Lower weight along thighs until feeling deep hamstring stretch.', 'Contract glutes and hamstrings to stand tall.'], tips: ['Knees remain soft, not bent further during descent.', 'Maintain flat back throughout.'] },
  { id: 'ex_cable_lat_pulldown', name: 'Cable Lat Pulldown', muscleGroup: 'Back', secondaryMuscles: ['Biceps'], equipment: 'Gym (Cable Machine)', isMinimalEquipment: false, difficulty: 'Beginner', instructions: ['Grip wide overhand bar.', 'Lean back 10-15 degrees with chest up.', 'Drive elbows down and back toward pockets until bar touches upper chest.', 'Control the eccentric stretch back to top.'], tips: ['Do not swing torso backward for momentum.', 'Focus on mind-muscle connection with lats.'] },
  { id: 'ex_leg_press', name: '45-Degree Leg Press', muscleGroup: 'Quadriceps', secondaryMuscles: ['Glutes'], equipment: 'Gym (Weight Machine)', isMinimalEquipment: false, difficulty: 'Beginner', instructions: ['Place feet shoulder-width on carriage platform.', 'Release safety locks and lower platform until knees are at 90 degrees.', 'Press through heels and mid-foot to starting position without hyperextending knees.'], tips: ['Never let lower back lift off pad at bottom.', 'Do not lock out knees aggressively.'] },
  { id: 'ex_cable_tricep', name: 'Cable Rope Tricep Pushdown', muscleGroup: 'Triceps', secondaryMuscles: [], equipment: 'Gym (Cable Machine)', isMinimalEquipment: false, difficulty: 'Beginner', instructions: ['Attach rope to high pulley.', 'Keep elbows pinned to sides.', 'Push down and spread rope handles at bottom contraction.', 'Return smoothly to 90-degree elbow angle.'], tips: ['Keep upper arms stationary.', 'Full lockout at bottom for peak contraction.'] },
  { id: 'ex_incline_db', name: 'Incline Dumbbell Press', muscleGroup: 'Chest', secondaryMuscles: ['Shoulders', 'Triceps'], equipment: 'Gym (Dumbbells)', isMinimalEquipment: false, difficulty: 'Beginner', instructions: ['Set bench to 30-45 degree incline.', 'Press dumbbells up over upper chest with palms facing forward.', 'Lower under control until deep stretch across clavicular head.'], tips: ['Avoid over-flaring elbows (maintain 60 deg angle).'] },

  // Minimal / Home Equipment
  { id: 'ex_pushup', name: 'Standard Push-Ups', muscleGroup: 'Chest', secondaryMuscles: ['Triceps', 'Core', 'Shoulders'], equipment: 'Minimal / Home (Bodyweight)', isMinimalEquipment: true, difficulty: 'Beginner', instructions: ['Hands slightly wider than shoulders on ground.', 'Plank position with core and glutes engaged.', 'Lower chest to 1 inch off floor.', 'Press up firmly.'], tips: ['Keep hips level with shoulders (no sagging).', 'Tuck elbows 45 degrees.'] },
  { id: 'ex_pullup', name: 'Pull-Ups / Chin-Ups', muscleGroup: 'Back', secondaryMuscles: ['Biceps', 'Core'], equipment: 'Minimal / Home (Pull-up Bar)', isMinimalEquipment: true, difficulty: 'Intermediate', instructions: ['Hang from bar with overhand or underhand grip.', 'Depress scapulae, pull chest up towards bar until chin clears bar.', 'Lower with full control to dead hang.'], tips: ['Avoid kipping/swinging.', 'Engage lats right before pulling.'] },
  { id: 'ex_db_squat', name: 'Goblet Squat (Dumbbell/Kettlebell)', muscleGroup: 'Quadriceps', secondaryMuscles: ['Glutes', 'Core'], equipment: 'Minimal / Home (Dumbbells)', isMinimalEquipment: true, difficulty: 'Beginner', instructions: ['Hold dumbbell or kettlebell vertically against chest.', 'Squat deep between knees while keeping elbows tucked.', 'Stand and lock glutes.'], tips: ['Keep torso upright.', 'Great for home leg strength and hip mobility.'] },
  { id: 'ex_db_lunge', name: 'Walking Dumbbell Lunges', muscleGroup: 'Quadriceps', secondaryMuscles: ['Glutes', 'Hamstrings', 'Calves'], equipment: 'Minimal / Home (Dumbbells)', isMinimalEquipment: true, difficulty: 'Beginner', instructions: ['Hold pair of dumbbells by sides.', 'Step forward, lowering back knee toward ground (both knees 90 deg).', 'Drive through front heel to step into next repetition.'], tips: ['Keep torso tall and balanced.', 'Do not let front knee cave inward.'] },
  { id: 'ex_db_curl', name: 'Standing Dumbbell Bicep Curl', muscleGroup: 'Biceps', secondaryMuscles: ['Core'], equipment: 'Minimal / Home (Dumbbells)', isMinimalEquipment: true, difficulty: 'Beginner', instructions: ['Hold dumbbells with palms forward or neutral.', 'Curl up while supinating wrists at top.', 'Lower slowly over 3 seconds.'], tips: ['No swinging lower back.', 'Squeeze biceps hard at peak.'] },
  { id: 'ex_db_lateral_raise', name: 'Dumbbell Lateral Raise', muscleGroup: 'Shoulders', secondaryMuscles: [], equipment: 'Minimal / Home (Dumbbells)', isMinimalEquipment: true, difficulty: 'Beginner', instructions: ['Hold dumbbells at sides with slight elbow bend.', 'Raise arms out to sides until parallel to ground (lead with elbows).', 'Control lower phase.'], tips: ['Slightly tilt pinkies up or keep thumbs level.', 'Do not shrug traps.'] },
  { id: 'ex_band_facepull', name: 'Resistance Band Face Pulls', muscleGroup: 'Shoulders', secondaryMuscles: ['Back'], equipment: 'Minimal / Home (Resistance Bands)', isMinimalEquipment: true, difficulty: 'Beginner', instructions: ['Anchor band at eye level.', 'Pull band towards face, separating hands and rotating thumbs backward.', 'Hold peak contraction for 1 second.'], tips: ['Superb for rear delt and rotator cuff shoulder health.'] },
  { id: 'ex_kb_swing', name: 'Kettlebell Russian Swing', muscleGroup: 'Glutes', secondaryMuscles: ['Hamstrings', 'Core', 'Back'], equipment: 'Minimal / Home (Kettlebell)', isMinimalEquipment: true, difficulty: 'Intermediate', instructions: ['Stand over kettlebell, hinge hips back.', 'Hike bell between legs, violently snap hips forward to float bell to chest height.', 'Allow bell to pull back into hinge.'], tips: ['Power comes 100% from hip snap, not lifting with arms.', 'Maintain rigid spine.'] },
  { id: 'ex_plank', name: 'Elbow Plank Hold', muscleGroup: 'Core', secondaryMuscles: ['Shoulders', 'Glutes'], equipment: 'Minimal / Home (Bodyweight)', isMinimalEquipment: true, difficulty: 'Beginner', instructions: ['Rest on forearms and toes.', 'Lock glutes, quads, and abdominal wall tightly.', 'Hold without sagging hips for 45-60 seconds.'], tips: ['Pull belly button up toward spine.'] },
  { id: 'ex_dips', name: 'Parallel Bar / Bench Dips', muscleGroup: 'Triceps', secondaryMuscles: ['Chest', 'Shoulders'], equipment: 'Minimal / Home (Bodyweight)', isMinimalEquipment: true, difficulty: 'Intermediate', instructions: ['Support bodyweight on parallel bars or sturdy bench edge.', 'Lower body until elbows are at 90 degrees.', 'Press up to lockout.'], tips: ['Keep chest up and avoid shoulders rolling forward.'] },
];

export const initialFormGuides: FormCorrectionGuide[] = [
  {
    id: 'guide_squat',
    exerciseName: 'Barbell Back Squat',
    muscleGroup: 'Quadriceps',
    svgVisualType: 'squat',
    summary: 'The king of lower body compound movements. Proper foot pressure, neutral lumbar spine, and hip-knee synchronicity are crucial for knee/back health.',
    correctFormPoints: [
      'Chest proud, shoulder blades retracted creating upper-back bar shelf.',
      'Feet shoulder-width apart, toes angled out 15-30 degrees.',
      'Knees track outward in line with 2nd and 3rd toes throughout entire descent.',
      'Hip crease drops below top of patella (parallel depth or below).',
      'Weight distributed evenly across tripod foot (heel, big toe ball, pinky ball).',
    ],
    dangerousMistakes: [
      {
        mistake: 'Knee Valgus (Knees Caving Inward)',
        risk: 'Excessive shear stress on ACL, meniscus, and patellofemoral joint.',
        correction: 'Actively push knees outward against an imaginary resistance band. Cue: "Screw feet into the floor".',
      },
      {
        mistake: 'Excessive Butt Wink & Lumbar Flexion at Bottom',
        risk: 'High risk of lumbar disc herniation and lower back strain.',
        correction: 'Only descend to the point where pelvis remains neutral. Improve ankle dorsiflexion & hip capsule mobility.',
      },
      {
        mistake: 'Good-Morning Squat (Hips Shoot Up First)',
        risk: 'Overloads lower back and disengages quadriceps leverage.',
        correction: 'Drive chest and traps up into the bar simultaneously with hip extension. Strengthen quads with front squats.',
      },
    ],
    setupSteps: [
      'Step under bar, set bar firmly across traps (high-bar) or rear delts (low-bar).',
      'Take 2-3 precise steps backward to set stance.',
      'Take deep diaphragmatic breath into belly and brace abs hard (Valsalva).',
    ],
    executionCues: [
      'Break hips and knees at the exact same moment.',
      'Descend smoothly over 2-3 seconds.',
      'Explode out of the hole pushing the floor away.',
    ],
    breathingCue: 'Inhale and brace 100% at top before descent. Exhale only once passing the sticking point near top.',
    jointAngleCheckpoints: [
      { joint: 'Knee Angle at Parallel', optimalAngle: '70° - 85°', tip: 'Knee tracking over toes is normal and safe with good ankle mobility.' },
      { joint: 'Torso Angle', optimalAngle: '45° - 65°', tip: 'Depends on femur length; keep spine strictly rigid regardless of angle.' },
      { joint: 'Ankle Dorsiflexion', optimalAngle: '35° - 45°', tip: 'Elevate heels with Olympic lifting shoes or plates if ankles are stiff.' },
    ],
    preLiftChecklist: [
      'Upper back shelf locked tight',
      'Stance width set & toes flared',
      'Deep 360-degree core breath braced',
      'Eyes forward/slightly downward',
    ],
  },
  {
    id: 'guide_deadlift',
    exerciseName: 'Conventional Barbell Deadlift',
    muscleGroup: 'Back',
    svgVisualType: 'deadlift',
    summary: 'The ultimate test of whole-body posterior chain power. Safety hinges on maintaining a neutral spinal column and dragging the barbell close against body.',
    correctFormPoints: [
      'Barbell positioned directly over mid-foot (1 inch away from shins before bending).',
      'Hips positioned higher than knees, lower than shoulders.',
      'Lats squeezed tight as if protecting armpits from tickling.',
      'Slack pulled completely out of the bar ("click" sound) before lifting.',
      'Bar path is 100% vertical and drags in contact with shins and thighs.',
    ],
    dangerousMistakes: [
      {
        mistake: 'Cat-Back Lumbar Rounding (Spinal Flexion Under Load)',
        risk: 'Severe disc bulge / spinal ligament rupture.',
        correction: 'Reset setup: push chest out, hinge deeply, lock lats down. Reduce weight if unable to maintain flat back.',
      },
      {
        mistake: 'Bar Drifting Forward Away from Body',
        risk: 'Creates a massive moment arm, drastically increasing torque on L4/L5 spine.',
        correction: 'Engage lats to drag the bar up your shins and quad thighs throughout the entire pull.',
      },
      {
        mistake: 'Hyperextending Lumbar Spine at Lockout',
        risk: 'Facet joint impingement and lower spine compression.',
        correction: 'Stand straight and squeeze glutes hard to finish the rep. Do not lean backward.',
      },
    ],
    setupSteps: [
      'Feet hip-width apart, bar over mid-foot laces.',
      'Bend over without moving bar, grip bar just outside shins.',
      'Bring shins forward until touching the bar.',
      'Pull chest up, squeeze lats, and wedge hips into position.',
    ],
    executionCues: [
      'Push the floor away like a leg press.',
      'Once bar passes knees, push hips forward into the bar.',
    ],
    breathingCue: 'Maximal air brace into abdomen at floor setup. Hold brace through concentric phase.',
    jointAngleCheckpoints: [
      { joint: 'Hip Height', optimalAngle: 'Intermediate (between knees & shoulders)', tip: 'Avoid squatting too low or starting with hips too high (stiff-leg).' },
      { joint: 'Arm Alignment', optimalAngle: 'Slightly behind shoulders', tip: 'Shoulder blades should sit directly over the bar.' },
    ],
    preLiftChecklist: [
      'Bar touches mid-foot',
      'Slack pulled out of barbell',
      'Lats engaged & armpits protected',
      'Neck in neutral alignment with spine',
    ],
  },
  {
    id: 'guide_bench',
    exerciseName: 'Barbell Flat Bench Press',
    muscleGroup: 'Chest',
    svgVisualType: 'bench_press',
    summary: 'The staple upper body pushing movement. Scapular retraction, arch stability, and diagonal bar path prevent rotator cuff impingement.',
    correctFormPoints: [
      'Shoulder blades retracted and depressed into bench pad.',
      'Feet planted firmly into the ground providing leg drive.',
      'Elbows tucked at 45-70 degrees to torso (avoid 90-degree T-flare).',
      'Bar touches lower-mid chest and follows a slight J-curve back over shoulders.',
      'Wrists straight and stacked over elbows.',
    ],
    dangerousMistakes: [
      {
        mistake: 'Elbows Flared 90° to Shoulders (T-Shape)',
        risk: 'Subacromial shoulder impingement and rotator cuff tears.',
        correction: 'Tuck elbows closer to ribs (arrow shape rather than T shape).',
      },
      {
        mistake: 'Bouncing Bar off Sternum / Ribcage',
        risk: 'Cartilage damage, sternal bruising, loss of chest tension.',
        correction: 'Lower with a controlled 2-second eccentric, touch chest gently, then press.',
      },
      {
        mistake: 'Lifting Hips/Glutes Off Bench Pad',
        risk: 'Disqualifying form, unstable base, excessive lower back hyperextension.',
        correction: 'Keep glutes pinned to bench while pushing feet into the ground for leg drive.',
      },
    ],
    setupSteps: [
      'Lie on bench with eyes under barbell.',
      'Retract scapulae back and down into pad.',
      'Grip bar with thumbs wrapped, wrists stacked.',
      'Unrack by pulling bar forward over shoulder joints.',
    ],
    executionCues: [
      'Pull bar down to sternum as if bending the bar in half.',
      'Drive through feet and press bar back toward eye line.',
    ],
    breathingCue: 'Inhale and brace at top. Lower bar, touch chest, press up and exhale past sticking point.',
    jointAngleCheckpoints: [
      { joint: 'Elbow Flare Angle', optimalAngle: '45° - 70°', tip: 'Never flare perpendicular to neck or shoulders.' },
      { joint: 'Forearm Verticality', optimalAngle: '90° at bottom', tip: 'Wrists must be directly above elbows at touch point.' },
    ],
    preLiftChecklist: [
      'Scapulae pinned and squeezed',
      'Glutes on bench & feet flat on floor',
      'Wrists neutral over knuckles',
      'Clear bar path over lower chest',
    ],
  },
  {
    id: 'guide_ohp',
    exerciseName: 'Standing Overhead Barbell Press',
    muscleGroup: 'Shoulders',
    svgVisualType: 'overhead_press',
    summary: 'Builds boulder shoulders and functional overhead stability. Demands core bracing to protect the lumbar spine.',
    correctFormPoints: [
      'Bar resting in heel of palms with vertical forearms.',
      'Glutes and quads locked tight creating a solid column.',
      'Head pulls back slightly to allow bar clearance, then pushes through ("window").',
      'Full lockout overhead with shrug at top for serratus activation.',
    ],
    dangerousMistakes: [
      {
        mistake: 'Excessive Back Arching (Turning OHP into Incline Bench)',
        risk: 'Severe lumbar spine compression and facet joint stress.',
        correction: 'Squeeze glutes 100% and pull ribs down. If arching occurs, weight is too heavy.',
      },
      {
        mistake: 'Pressing Bar in Arc Forward Around Face',
        risk: 'Lost mechanical advantage and shoulder strain.',
        correction: 'Move head out of the way; keep the barbell moving in a strictly straight vertical line.',
      },
    ],
    setupSteps: [
      'Grip bar just outside shoulder width.',
      'Step under bar, unrack onto front delts, take 2 steps back.',
      'Squeeze glutes, quads, and abs.',
    ],
    executionCues: [
      'Push bar straight up brushing past nose.',
      'Push head through window once bar clears forehead.',
      'Lock out overhead with active traps.',
    ],
    breathingCue: 'Inhale and brace at chin level. Exhale at top lockout.',
    jointAngleCheckpoints: [
      { joint: 'Forearm Angle at Bottom', optimalAngle: '90° vertical', tip: 'Elbows slightly in front of bar.' },
    ],
    preLiftChecklist: [
      'Glutes squeezed tight',
      'Core braced',
      'Forearms vertical',
      'Straight vertical path visualized',
    ],
  },
  {
    id: 'guide_barbell_row',
    exerciseName: 'Bent-Over Barbell Row',
    muscleGroup: 'Back',
    svgVisualType: 'barbell_row',
    summary: 'Essential for upper back thickness and lat development. Maintaining a stable hinge without swinging is the key to safety and gains.',
    correctFormPoints: [
      'Torso angled between 45° and parallel to floor with neutral spine.',
      'Pull elbows toward hips/pockets rather than straight up.',
      'Squeeze shoulder blades together at top contraction.',
      'Lower bar with full control into lat stretch.',
    ],
    dangerousMistakes: [
      {
        mistake: 'Using Torso Heaving / Momentum (Ego Lifting)',
        risk: 'Disengages lats and puts lower back at sudden jarring risk.',
        correction: 'Keep torso stationary. Pull exclusively using upper back musculature.',
      },
      {
        mistake: 'Rounding Lumbar Spine During Pull',
        risk: 'Disk herniation under static spinal load.',
        correction: 'Maintain active hip hinge with flat spine and engaged core.',
      },
    ],
    setupSteps: [
      'Deadlift bar up, then hinge hips back to 45° torso angle.',
      'Let arms hang naturally under shoulders.',
    ],
    executionCues: [
      'Drive elbows backward into ceiling/ribs.',
      'Hold contraction for 1 second at top.',
    ],
    breathingCue: 'Inhale at bottom hang. Exhale as you row bar into abdomen.',
    jointAngleCheckpoints: [
      { joint: 'Torso Angle', optimalAngle: '35° - 50°', tip: 'Avoid standing too upright (shrugging traps instead of lats).' },
    ],
    preLiftChecklist: ['Spine flat', 'Hips pushed back', 'Weight in mid-foot', 'Elbows primed to drive back'],
  },
  {
    id: 'guide_rdl',
    exerciseName: 'Romanian Deadlift (RDL)',
    muscleGroup: 'Hamstrings',
    svgVisualType: 'rdl',
    summary: 'The ultimate hamstring and glute builder. Emphasizes pure hip hinge mechanics while keeping the shins vertical.',
    correctFormPoints: [
      'Knees soft (slight 15° bend), but remaining stationary throughout movement.',
      'Hips push horizontally backward as if reaching for a wall 2 feet behind you.',
      'Barbell/dumbbells stay glued against thighs and shins.',
      'Stop descent when hips stop moving back (typically just below knees).',
    ],
    dangerousMistakes: [
      {
        mistake: 'Bending Knees into a Squat',
        risk: 'Removes tension from hamstrings and transfers to quads.',
        correction: 'Keep shins perpendicular to the floor. Only hips move backward.',
      },
      {
        mistake: 'Reaching for the Floor with Arms and Rounding Back',
        risk: 'Spinal flexion and zero extra hamstring benefit.',
        correction: 'Descent ends when your hips cannot reach any further back.',
      },
    ],
    setupSteps: ['Stand tall holding weight, soft knees, chest tall.'],
    executionCues: ['Push hips back, feel intense stretch in hamstrings, snap hips forward to return.'],
    breathingCue: 'Inhale and brace at top. Exhale as you drive hips forward to lockout.',
    jointAngleCheckpoints: [{ joint: 'Knee Bend', optimalAngle: '15° - 20° fixed', tip: 'Never lock out 100% or bend past 30°.' }],
    preLiftChecklist: ['Soft knees', 'Chest tall', 'Weight kept on thighs', 'Hips ready to hinge back'],
  },
  {
    id: 'guide_pullup',
    exerciseName: 'Strict Pull-Ups',
    muscleGroup: 'Back',
    svgVisualType: 'pull_up',
    summary: 'The gold standard for vertical pulling strength. Full range of motion from dead hang to chin-over-bar.',
    correctFormPoints: [
      'Full dead hang stretch at bottom with engaged shoulders.',
      'Initiate pull by pulling shoulder blades down and back.',
      'Chest reaches toward bar, chin clears bar without craning neck.',
      'Lower under control over 2 seconds.',
    ],
    dangerousMistakes: [
      {
        mistake: 'Excessive Kipping / Kicking Legs',
        risk: 'Shoulder labrum and bicep tendon strain.',
        correction: 'Cross ankles, engage abs, and perform slow strict reps.',
      },
      {
        mistake: 'Half Reps (Failing to reach full dead hang)',
        risk: 'Leaves lower lats underdeveloped and limits strength gains.',
        correction: 'Full extension at the bottom of every rep.',
      },
    ],
    setupSteps: ['Grip bar overhand just outside shoulder width.'],
    executionCues: ['Drive elbows down to ribs, lead with chest.'],
    breathingCue: 'Exhale on the pull up, inhale as you lower.',
    jointAngleCheckpoints: [{ joint: 'Elbow Range', optimalAngle: '180° bottom to <45° top', tip: 'Full lockout at bottom.' }],
    preLiftChecklist: ['Dead hang established', 'Core locked', 'Shoulders depressed before pull'],
  },
  {
    id: 'guide_curl',
    exerciseName: 'Bicep Dumbbell Curl',
    muscleGroup: 'Biceps',
    svgVisualType: 'bicep_curl',
    summary: 'Direct bicep isolation. Strict form isolates the biceps brachii and prevents front delt / lower back compensation.',
    correctFormPoints: [
      'Elbows pinned at sides and slightly in front of hips.',
      'Supinate wrist (rotate pinky up toward ceiling) through top half of curl.',
      'Control eccentric lowering phase for 3 seconds.',
    ],
    dangerousMistakes: [
      {
        mistake: 'Swinging Torso and Shoulders Backward',
        risk: 'Lower back strain and zero bicep overload.',
        correction: 'Stand against a wall to practice strict elbow flexion.',
      },
    ],
    setupSteps: ['Stand with dumbbells at sides, palms facing inward or forward.'],
    executionCues: ['Squeeze bicep, rotate wrist outwards, pin elbow in space.'],
    breathingCue: 'Exhale on curl, inhale on slow descent.',
    jointAngleCheckpoints: [{ joint: 'Elbow Position', optimalAngle: 'Fixed beside torso', tip: 'Do not let elbow drift backward.' }],
    preLiftChecklist: ['Chest proud', 'Elbows pinned', 'No swinging'],
  },
  {
    id: 'guide_lunge',
    exerciseName: 'Walking Dumbbell Lunges',
    muscleGroup: 'Quadriceps',
    svgVisualType: 'lunge',
    summary: 'Unilateral leg strength, glute activation, and balance.',
    correctFormPoints: [
      'Step forward with both knees bending to 90 degrees at bottom.',
      'Back knee hovers 1 inch off the floor.',
      'Front knee stays centered over front foot.',
      'Torso remains upright with engaged core.',
    ],
    dangerousMistakes: [
      {
        mistake: 'Front Knee Collapsing Inward (Valgus)',
        risk: 'Knee ligament torque and patellar tracking pain.',
        correction: 'Focus on pushing knee slightly outward over pinky toe.',
      },
    ],
    setupSteps: ['Hold dumbbells by sides, stand tall.'],
    executionCues: ['Step forward smoothly, lower straight down, drive up through front heel.'],
    breathingCue: 'Inhale during step/descent, exhale as you step up.',
    jointAngleCheckpoints: [{ joint: 'Front & Back Knee', optimalAngle: '90° at bottom', tip: 'Avoid short strides that jam front knee.' }],
    preLiftChecklist: ['Torso tall', 'Stride length measured', 'Weight in front heel'],
  },
  {
    id: 'guide_lateral_raise',
    exerciseName: 'Dumbbell Lateral Raise',
    muscleGroup: 'Shoulders',
    svgVisualType: 'lateral_raise',
    summary: 'The premier exercise for lateral deltoid width and the 3D shoulder look.',
    correctFormPoints: [
      'Lean torso forward 10-15 degrees.',
      'Slight bend in elbows (15°), lead movement with elbows.',
      'Raise until arms are parallel to floor in the scapular plane (30° forward of body).',
      'Lower smoothly without bouncing.',
    ],
    dangerousMistakes: [
      {
        mistake: 'Shrugging Traps to Neck to Hoist Dumbbells',
        risk: 'Upper trap dominance, neck stiffness, lack of delt stimulus.',
        correction: 'Push hands outward toward walls rather than upward. Keep traps relaxed.',
      },
    ],
    setupSteps: ['Hold dumbbells in front of thighs with slight forward torso tilt.'],
    executionCues: ['Pour out water at the top, lead with elbows, control down.'],
    breathingCue: 'Exhale on lift, inhale on lower.',
    jointAngleCheckpoints: [{ joint: 'Arm Elevation', optimalAngle: '90° parallel', tip: 'Raising above shoulder level over-engages traps.' }],
    preLiftChecklist: ['Torso slightly tilted', 'Shoulders depressed', 'Elbows leading'],
  },
];

export const initialMeetups: BiWeeklyMeetup[] = [
  {
    id: 'meetup_1',
    clientId: 'user_alex',
    clientName: 'Alex Rivers',
    clientAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    coachId: 'coach_pat',
    coachName: 'Coach Pat',
    date: '2026-08-22',
    time: '10:00 AM - 11:00 AM',
    location: 'Metro Elite Strength Gym — Assessment Room B',
    cycleNumber: 5,
    status: 'Scheduled',
    agenda: [
      'InBody Body Composition Scan (Weight, Muscle Mass, Visceral Fat)',
      'Review Squat & Bench Press video form recordings',
      'Calorie & Macronutrient target adjustment for Cycle 5 (+150 kcal surplus)',
      'Mobility screening for right ankle dorsiflexion',
      'Next 2-week training block assignment (Hypertrophy Block 3)',
    ],
    inBodyScan: {
      weightKg: 76.8,
      skeletalMuscleKg: 38.2,
      bodyFatPercent: 15.1,
      visceralFatLevel: 4,
      waterPercent: 62.4,
    },
    physicalScreeningNotes: 'Overall posture balanced. Right ankle showed slight limitation on deep squat knee travel (prescribed banded ankle distractions).',
    coachPrescriptions: [
      'Add 150 kcal daily (Target: 2,650 kcal, 175g protein).',
      'Implement 5-minute pre-squat ankle mobility warmup.',
      'Progressive overload target: Bench Press 97.5kg for 5 reps in next 2 weeks.',
    ],
    coachNotes: 'Alex is making outstanding progress on the lean bulk phase! Next physical check-in set for 2 weeks from meetup date.',
  },
  {
    id: 'meetup_past_1',
    clientId: 'user_alex',
    clientName: 'Alex Rivers',
    clientAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    coachId: 'coach_pat',
    coachName: 'Coach Pat',
    date: '2026-08-08',
    time: '10:00 AM - 11:00 AM',
    location: 'Metro Elite Strength Gym — Assessment Room B',
    cycleNumber: 4,
    status: 'Completed',
    agenda: [
      'Cycle 4 InBody Assessment',
      'Weightlifting volume progression check',
      'Nutrition adherence review',
    ],
    inBodyScan: {
      weightKg: 76.2,
      skeletalMuscleKg: 37.6,
      bodyFatPercent: 15.4,
      visceralFatLevel: 4,
      waterPercent: 62.0,
    },
    physicalScreeningNotes: 'Shoulder mobility tested excellent. Scapular control on bench press is solid.',
    coachPrescriptions: [
      'Maintained 2,500 kcal.',
      'Added weighted pull-ups to Pull day.',
    ],
    coachNotes: 'Client logged 5/5 workouts for the 2-week cycle. Excellent consistency.',
  },
];

export const initialCoachClients: ClientCoachRecord[] = [
  {
    clientId: 'user_alex',
    clientName: 'Alex Rivers',
    clientEmail: 'alex.rivers@fitness.app',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    joinDate: '2026-06-20',
    currentPhase: 'Hypertrophy / Lean Bulk Phase 2',
    targetCalories: 2650,
    targetProteinG: 175,
    targetCarbsG: 300,
    targetFatG: 70,
    targetWorkoutsPerWeek: 5,
    adherenceScorePercent: 96,
    lastCheckInDate: '2026-08-08',
    nextMeetupDate: '2026-08-22',
    coachNotes: 'Alex is hitting all weekly lifting targets. Scheduled for bi-weekly physical check-in this Saturday.',
    assignedWorkoutProgram: '5-Day Upper/Lower Strength & Hypertrophy Split',
    formReviewAlerts: ['Right ankle dorsiflexion drill checked on squats', 'Bench press arch validated'],
  },
  {
    clientId: 'client_marcus',
    clientName: 'Marcus Vance',
    clientEmail: 'marcus.v@fitness.app',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    joinDate: '2026-07-01',
    currentPhase: 'Body Recomposition & Strength',
    targetCalories: 2300,
    targetProteinG: 180,
    targetCarbsG: 220,
    targetFatG: 60,
    targetWorkoutsPerWeek: 4,
    adherenceScorePercent: 91,
    lastCheckInDate: '2026-08-12',
    nextMeetupDate: '2026-08-26',
    coachNotes: 'Deadlift mechanics improved significantly after hip-hinge focus. Keep protein at 180g.',
    assignedWorkoutProgram: '4-Day Push / Pull Split',
    formReviewAlerts: ['Deadlift spine neutral verified'],
  },
  {
    clientId: 'client_elena',
    clientName: 'Elena Rostova',
    clientEmail: 'elena.r@fitness.app',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    joinDate: '2026-07-15',
    currentPhase: 'Fat Loss & Athletic Conditioning',
    targetCalories: 1850,
    targetProteinG: 145,
    targetCarbsG: 170,
    targetFatG: 50,
    targetWorkoutsPerWeek: 4,
    adherenceScorePercent: 88,
    lastCheckInDate: '2026-08-15',
    nextMeetupDate: '2026-08-29',
    coachNotes: 'Down 2.2kg over 4 weeks. Muscle retention high. Recommend electrolyte drink on training days.',
    assignedWorkoutProgram: '4-Day Full Body & Conditioning Protocol',
    formReviewAlerts: ['Squat depth verified'],
  },
];

export const initialPaymentPlans: PaymentPlan[] = [
  {
    id: 'plan_basic',
    title: 'Basic Fitness Tracker',
    priceUsd: 19,
    period: 'per month',
    description: 'Complete self-tracking suite for gym athletes and home workouts.',
    features: [
      'Full Food & Nutrition Tracker with Macro Breakdown',
      'Weightlifting Logger with 1RM Calculator & Volume Graph',
      'Physique Photo & Measurement Tracker',
      'Workout Frequency Heatmap & Streak Tracker',
      'Complete 60+ Exercise Library & Custom Exercise Creator',
    ],
    qrPayload: 'https://pay.fitnesscoach.app/qr/basic-tier/alex-rivers-19',
  },
  {
    id: 'plan_pro',
    title: 'Pro Athlete Tier',
    priceUsd: 39,
    period: 'per month',
    badge: 'MOST POPULAR',
    popular: true,
    description: 'Advanced analytics, visual form correction guides, and automated nutrition targets.',
    features: [
      'Everything in Basic Tracker',
      'Interactive Exercise Form Correction & Checklist',
      'Interactive Before/After Physique Comparison Slider',
      'Rest Timer with Audio/Visual Alerts & PR Celebration',
      'Priority Workout Split Builder & Export Reports',
    ],
    qrPayload: 'https://pay.fitnesscoach.app/qr/pro-athlete/alex-rivers-39',
  },
  {
    id: 'plan_elite',
    title: '1-on-1 Elite Coaching with Coach Pat',
    priceUsd: 99,
    period: 'per month',
    badge: 'COACH MONITORED',
    description: 'Direct coaching with Head Coach Pat and staff trainers, including bi-weekly physical meet-ups.',
    features: [
      'Everything in Pro Athlete',
      'Bi-Weekly (every 2 weeks) Physical Meet-ups with Coach Pat',
      'In-person InBody Body Composition & Mobility Screening',
      'Direct Coach Dashboard Monitoring & Metric Adjustments',
      'Personalized Workout Program & Macro Prescriptions',
      'Direct Coach Form Video Audits & 24/7 Coaching Notes',
    ],
    qrPayload: 'https://pay.fitnesscoach.app/qr/coach-pat-elite/alex-rivers-99',
  },
];

export const initialTransactions: PaymentTransaction[] = [
  {
    id: 'tx_108',
    date: '2026-08-01',
    planId: 'plan_elite',
    planTitle: '1-on-1 Elite Coaching with Coach Pat',
    amountUsd: 99,
    method: 'QR_GCASH',
    qrReferenceCode: 'GCASH-REF-89421048',
    status: 'Completed',
    invoiceNumber: 'INV-2026-0801-99',
    payerName: 'Alex Rivers',
  },
  {
    id: 'tx_107',
    date: '2026-07-01',
    planId: 'plan_elite',
    planTitle: '1-on-1 Elite Coaching with Coach Pat',
    amountUsd: 99,
    method: 'QR_PROMPTPAY',
    qrReferenceCode: 'PPAY-REF-77312019',
    status: 'Completed',
    invoiceNumber: 'INV-2026-0701-99',
    payerName: 'Alex Rivers',
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif_1',
    title: 'Bi-Weekly Meet-up Scheduled with Coach Pat',
    message: 'Your next physical check-in is scheduled for Saturday, Aug 22 at 10:00 AM in Assessment Room B.',
    type: 'meetup',
    timestamp: '2 hours ago',
    read: false,
    linkUrl: '/coach-dashboard',
  },
  {
    id: 'notif_2',
    title: 'New Personal Record (PR) Achieved! 🏆',
    message: 'Congratulations! You hit 95kg for 5 reps on Barbell Bench Press (Estimated 1RM: 107kg).',
    type: 'workout',
    timestamp: 'Yesterday',
    read: false,
    linkUrl: '/workouts',
  },
  {
    id: 'notif_3',
    title: 'Daily Nutrition Reminder',
    message: "You have 68g of protein remaining to reach today's target of 175g.",
    type: 'nutrition',
    timestamp: '5 hours ago',
    read: true,
    linkUrl: '/food',
  },
  {
    id: 'notif_4',
    title: 'Coach Pat Left a Note',
    message: '"Awesome waist-to-shoulder ratio improvement! Adding 100 kcal on leg days."',
    type: 'coach',
    timestamp: '2 days ago',
    read: true,
    linkUrl: '/physique',
  },
];
